POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit matheus",
  "details": "Um evento para apaixonados",
  "maximumAttendees": 100
}

###

POST http://localhost:3333/events/95b2fdfd-832b-4c8c-9680-05717c54c6d8/attendees
Content-Type: application/json

{
  "name": "Matheus Henrique",
  "email": "mathes@test.com"
}

###

GET http://localhost:3333/events/95b2fdfd-832b-4c8c-9680-05717c54c6d8

###

GET http://localhost:3333/attendees/5/badge

###

POST http://localhost:3333/attendees/5/check-in

###

GET http://localhost:3333/events/95b2fdfd-832b-4c8c-9680-05717c54c6d8/attendees?query=Matheus